# Generated by Django 4.2.20 on 2025-05-12 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LocationModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "country",
                    models.CharField(db_index=True, max_length=200, unique=True),
                ),
                ("district", models.CharField(max_length=200, unique=True)),
                ("division", models.CharField(max_length=200, unique=True)),
                ("local_address", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "unique_together": {("country", "district", "division")},
            },
        ),
    ]
