# Generated by Django 4.2.20 on 2025-05-12 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productmodel",
            name="product_image",
            field=models.ImageField(blank=True, null=True, upload_to="product_images/"),
        ),
    ]
